#!/bin/bash
#PBS -l nodes=hartree:ppn=4,walltime=1:00:00
#PBS -N ZnO-RS-bandspp
#PBS -j oe
#PBS -V
source /opt/intel/bin/compilervars.sh intel64
cd $PBS_O_WORKDIR
/home/s/root/bin/mpirun -np 4 /home/toth/Software/qe.6.3.0/bin/bands.x < ZnO-RS.bandspp.in > ZnO-RS.bandspp.out
# plot bands to bands.pdf file
python3 qe_bands_plot.py
